import { HugeiconsIcon } from "@hugeicons/react-native";
import {
  Home01Icon,
  UserGroupIcon,
  UserIcon,
  FootballIcon,
  ShoppingCart01Icon,
  Shield01Icon,
  Shield02Icon,
  CoinsDollarIcon,
  DiamondIcon,
  EnergyIcon,
  PlusSignIcon,
  Clock01Icon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  RunningShoesIcon,
  StarIcon,
  ViewIcon,
  CheckmarkCircle01Icon,
  CircleIcon,
  Alert02Icon,
  CubeIcon,
  Notification03Icon,
  TradeUpIcon,
  TradeDownIcon,
  MinusSignIcon,
  Exchange01Icon,
  Target01Icon,
  FavouriteIcon,
  GridViewIcon,
  Search01Icon,
  FilterHorizontalIcon,
  FireIcon,
  SnowIcon,
  ThermometerIcon,
  TShirtIcon,
  File01Icon,
  WorkflowSquare01Icon,
  Bookmark01Icon,
  GlobeIcon,
  AgreementIcon,
  Tag01Icon,
  PulseIcon,
  Wallet01Icon,
  WrenchIcon,
  Building01Icon,
  DumbbellIcon,
  MortarboardIcon,
  Medicine01Icon,
} from "@hugeicons/core-free-icons";
import { color as palette } from "@/theme";

/**
 * Ícones do app: Hugeicons (set free) como padrão. Um único wrapper mapeia
 * nomes semânticos → ícones Hugeicons, então as telas continuam usando nomes
 * estáveis (`<Icon name="football" />`) sem acoplar ao pacote de ícones.
 */
const MAP = {
  home: Home01Icon,
  people: UserGroupIcon,
  person: UserIcon,
  football: FootballIcon,
  cart: ShoppingCart01Icon,
  shield: Shield01Icon,
  "shield-half": Shield02Icon,
  "logo-usd": CoinsDollarIcon,
  diamond: DiamondIcon,
  flash: EnergyIcon,
  add: PlusSignIcon,
  time: Clock01Icon,
  "time-outline": Clock01Icon,
  "chevron-forward": ArrowRight01Icon,
  "chevron-down": ArrowDown01Icon,
  "chevron-up": ArrowUp01Icon,
  "arrow-back": ArrowLeft01Icon,
  "arrow-forward": ArrowRight01Icon,
  "arrow-up": ArrowUp01Icon,
  "arrow-down": ArrowDown01Icon,
  "arrow-up-circle": ArrowUp01Icon,
  "arrow-down-circle": ArrowDown01Icon,
  walk: RunningShoesIcon,
  star: StarIcon,
  "star-outline": StarIcon,
  eye: ViewIcon,
  "checkmark-circle": CheckmarkCircle01Icon,
  ellipse: CircleIcon,
  warning: Alert02Icon,
  cube: CubeIcon,
  notifications: Notification03Icon,
  "notifications-outline": Notification03Icon,
  "trending-up": TradeUpIcon,
  "trending-down": TradeDownIcon,
  remove: MinusSignIcon,
  "swap-horizontal": Exchange01Icon,
  locate: Target01Icon,
  heart: FavouriteIcon,
  grid: GridViewIcon,
  search: Search01Icon,
  "search-circle": Search01Icon,
  options: FilterHorizontalIcon,
  flame: FireIcon,
  snow: SnowIcon,
  thermometer: ThermometerIcon,
  shirt: TShirtIcon,
  "document-text": File01Icon,
  "git-network": WorkflowSquare01Icon,
  bookmark: Bookmark01Icon,
  globe: GlobeIcon,
  "hand-left": AgreementIcon,
  pricetag: Tag01Icon,
  pulse: PulseIcon,
  wallet: Wallet01Icon,
  construct: WrenchIcon,
  business: Building01Icon,
  barbell: DumbbellIcon,
  school: MortarboardIcon,
  medkit: Medicine01Icon,
} as const;

export type IconName = keyof typeof MAP;

export function Icon({
  name,
  size = 20,
  color = palette.text,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  return <HugeiconsIcon icon={MAP[name] ?? CircleIcon} size={size} color={color} strokeWidth={strokeWidth} />;
}
